#define VEHICLE_ITEMLIST                42100
#define VEHICLE_ITEMLISTTITLEVEHICLE    42101
#define VEHICLE_ITEMLISTTITLE           42102
#define VEHICLE_TAKEBUTTON              42103
#define VEHICLE_STOREBUTTON             42104

#define VEHICLE_BG_W                    (3*MENU_PADDING_X + 4*MENU_COLUMN_W + 2*MENU_ITEMSPACE_X + MENU_ITEM_W)
#define VEHICLE_BG_X                    CENTER(1, VEHICLE_BG_W)

#define VEHICLE_COLUMN1_X               (VEHICLE_BG_X + MENU_PADDING_X)
#define VEHICLE_BUTTON_X                (VEHICLE_COLUMN1_X + MENU_COLUMN_W + MENU_ITEMSPACE_X)
#define VEHICLE_COLUMN2_X               (VEHICLE_BUTTON_X + MENU_ITEM_W + MENU_ITEMSPACE_X)
#define VEHICLE_COLUMN3_X               (VEHICLE_COLUMN2_X + MENU_COLUMN_W + MENU_PADDING_X)

#define VEHICLE_BUTTON_Y                CENTER(1, 2*MENU_ITEM_H + MENU_ITEMSPACE_Y)
