////////////////////////////////////////////////////////
// GUI EDITOR OUTPUT START (by Sacher, v1.063, #Dyroxu)
////////////////////////////////////////////////////////

#define ARTIWIDTHMAINSPACE  0.25
#define ARTIHEIGHTMAINSPACE  0.15
#define ARTILAYOUTHEIGHT   0.05
#define ARTILAYOUTHEIGHTSPACE   0.055
#define ARTIBORDERTHICKNESS   0.01
#define ARTILAYOUTWIDTH   0.15
#define ARTILAYOUTWIDTHSPACE   0.16

#define POFM_DIA_IDD_DISPLAY 772
#define POFM_DIA_IDC_GUNSELECT 29395
#define POFM_DIA_IDC_SHELLSELECT 29396
#define POFM_DIA_IDC_GRID 29397
#define POFM_DIA_IDC_MILS 29398
#define POFM_DIA_IDC_DISTANCE 29399
#define POFM_DIA_IDC_DISPERSION 29400
#define POFM_DIA_IDC_BURSTNUMBER 29401
#define POFM_DIA_IDC_BURSTROUNDS 29402
#define POFM_DIA_IDC_BURSTDELAY 29403
#define POFM_DIA_IDC_NUMGUNSELECT 29405
