
// actionKey that activates the clicker sound. This will determine the binded key for the action
// actionKey names can be found at https://community.bistudio.com/wiki/inputAction/actions
GVAR(actionKey) = "nightVision";

// array of possible randomly selected clicker sounds, in .ogg format.
GVAR(soundArray) = ["cricket1.ogg"];

// level of volume generated by clicker. 1 - 2 are recommended, 5 is max.
GVAR(volume) = 1;
